# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Global test of beta for moderate-dimensional inferences using Rcpp
#' @name beta_P_value
#' @description Global test of beta for moderate-dimensional inferences using Rcpp
#' @param X a numeric matrix
#' @param Y a numeric vector
#' @param beta the null beta
#' @return P value of beta global test in moderate-dimensional
#' @examples
#' \dontrun{
#' n=1000
#' pn=900
#' beta<-runif(pn)
#' sigma<-runif(n)
#' X<-matrix(rnorm(pn*n),nrow = n,ncol = pn)
#' epsilon<-numeric(n)
#' for(j in 1:n)epsilon[j]<-rnorm(1,mean = 0,sd = sigma)
#' Y<-X%*%beta+epsilon
#' beta_P_value(Y,X,rep(0,pn))
#' beta_P_value(Y,X,beta)
#' }
#' @export
beta_P_value <- function(Y, X, beta) {
    .Call('_SA23204166_beta_P_value', PACKAGE = 'SA23204166', Y, X, beta)
}

